pipeline {
    agent {
        docker {
            // image 'node:lts-buster-slim'
            image 'node:16-buster-slim' 
            args '-p 3001:3001'
        }
    }
    // environment {
    //     CI = 'true'
    // }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('ManualApproval') {
            steps {
                input message: 'Lanjutkan ke tahap deploy? (Klik "Proceed" untuk melanjutkan ke tahap deploy)' 
            }
        }
        stage('Deploy') { 
            steps {
                // input message: 'Lanjutkan ke tahap deploy? (Klik "Proceed" untuk melanjutkan ke tahap deploy)' 
                sh './jenkins/scripts/deliver.sh' 
                // sh 'sleep 60'
                // sh './jenkins/scripts/kill.sh' 
            }
        }
    }
}
